kubedb/docs

- DCO
- LICENSE
> Add License & DCO

- docs/guides/mysql/quickstart/quickstart.md
This PR fixes a typo in the relevant doc.
> Fix typo in mysql-quickstart guide

- .github/workflows/ci.yml
> Check for broken links

- docs/setup/install.md
> Add Helm 3 instructions

- docs/guides/postgres/snapshot/wal/archiving_to_minio.md
- docs/guides/postgres/snapshot/wal/archiving_to_s3.md
> S3 endpoint related fixes

- docs/setup/install.md
> Always create rbac resources

- docs/guides/elasticsearch/kibana/connect-kibana.md
> fix typo yaml -> yml

- docs/setup/install.md
- docs/setup/monitoring/builtin.md
- docs/setup/monitoring/coreos.md
- docs/setup/monitoring/overview.md
- docs/setup/uninstall.md
- Make helm 3 recommended method
- Rewrite script to use helm 3
> Update installation instructions

- hack/scripts/open-pr.sh
> Add script to open pr

- docs/reference/operator/_index.md
- docs/reference/operator/kubedb-operator.md
- docs/reference/operator/kubedb-operator_run.md
- docs/reference/operator/kubedb-operator_version.md
> Update docs for kubedb/operator@c888d7fd

- docs/reference/operator/kubedb-operator_run.md
> Update docs for kubedb/operator@ba436a4b

- docs/guides/mysql/snapshot/backup-and-restore.md
corrected typo, should be sql instead of bson
> Use correct file type in backup-and-restore.md

- docs/reference/cli/kubectl-dba_completion.md
> Update docs for kubedb/cli@4e46c763

- docs/reference/operator/kubedb-operator.md
- docs/reference/operator/kubedb-operator_run.md
- docs/reference/operator/kubedb-operator_version.md
> Update docs for kubedb/operator@f03305e1

- docs/reference/operator/kubedb-operator_run.md
> Update docs for kubedb/operator@8fd3b682

- docs/reference/operator/kubedb-operator_run.md
> Update docs for kubedb/operator@07d63285

- docs/setup/install/community.md
- docs/setup/uninstall/community.md
> Use release name kubedb-community for community chart

- docs/setup/install/community.md
- docs/setup/install/enterprise.md
> Fix enterprise installation instructions

- docs/reference/cli/kubectl-dba_version.md
> Update docs for kubedb/cli@4d348dbd

- docs/reference/operator/kubedb-operator.md
- docs/reference/operator/kubedb-operator_run.md
- docs/reference/operator/kubedb-operator_version.md
> Update docs for kubedb/operator@9e12a91f

- .github/workflows/ci.yml
- docs/examples/mongodb/clustering/mongo-sharding.yaml
- docs/guides/memcached/cli/cli.md
- docs/guides/memcached/quickstart/quickstart.md
- docs/guides/mongodb/clustering/sharding.md
- docs/guides/mongodb/concepts/mongodb.md
- docs/guides/percona-xtradb/clustering/percona-xtradb-cluster.md
- docs/guides/percona-xtradb/initialization/using-script.md
- docs/guides/percona-xtradb/quickstart/quickstart.md
> Remove RollingUpdate strategy

- docs/setup/install/community.md
- docs/setup/install/enterprise.md
> Use updated crd label app.kubernetes.io/name=kubedb

- docs/examples/elasticsearch/es-overview.yaml
- docs/examples/mongodb/Initialization/demo-1.yaml
- docs/examples/mysql/Initialization/demo-1.yaml
- docs/examples/percona-xtradb/px-init-script.yaml
- docs/examples/postgres/initialization/script-postgres.yaml
- docs/examples/postgres/pg-overview.yaml
- docs/guides/elasticsearch/concepts/elasticsearch.md
- docs/guides/mongodb/concepts/mongodb.md
- docs/guides/mongodb/initialization/using-script.md
- docs/guides/mysql/concepts/mysql.md
- docs/guides/mysql/initialization/using-script.md
- docs/guides/percona-xtradb/concepts/percona-xtradb.md
- docs/guides/percona-xtradb/initialization/using-script.md
- docs/guides/postgres/concepts/postgres.md
- docs/guides/postgres/initialization/script_source.md
Seems like scriptSource was renamed
> Update init.script field documentation

- docs/setup/install/enterprise.md
- docs/setup/uninstall/enterprise.md
> Add autoscaler installation instructions

- docs/examples/monitoring/builtin-prometheus/prom-config.yaml
- docs/guides/elasticsearch/monitoring/using-builtin-prometheus.md
- docs/guides/memcached/monitoring/using-builtin-prometheus.md
- docs/guides/mongodb/monitoring/using-builtin-prometheus.md
- docs/guides/mysql/clients/mysql-cluster.md
- docs/guides/mysql/monitoring/using-builtin-prometheus.md
- docs/guides/percona-xtradb/monitoring/using-builtin-prometheus.md
- docs/guides/pgbouncer/monitoring/using-builtin-prometheus.md
- docs/guides/postgres/monitoring/using-builtin-prometheus.md
- docs/guides/proxysql/monitoring/using-builtin-prometheus.md
- docs/guides/redis/monitoring/using-builtin-prometheus.md
> Fix labels for monitoring

- docs/examples/elasticsearch/clustering/topology-es.yaml
- docs/examples/elasticsearch/custom-config/es-custom-with-topology.yaml
- docs/guides/elasticsearch/clustering/topology.md
- docs/guides/elasticsearch/concepts/elasticsearch.md
- docs/guides/elasticsearch/configuration/with-topology.md
> Change the prefix to suffix  for Elasticsearch

- docs/setup/install/community.md
- docs/setup/install/enterprise.md
> Update YAML install instructions

- docs/examples/redis/scaling/rd-cluster.yaml
- docs/examples/redis/scaling/rd-standalone.yaml
- docs/examples/redis/scaling/vertical-cluster.yaml
- docs/examples/redis/scaling/vertical-standalone.yaml
- docs/examples/redis/upgrading/rd-cluster.yaml
- docs/examples/redis/upgrading/rd-standalone.yaml
- docs/examples/redis/upgrading/upgrade-cluster.yaml
- docs/examples/redis/upgrading/upgrade-standalone.yaml
- docs/guides/redis/scaling/_index.md
- docs/guides/redis/scaling/horizontal-scaling/_index.md
- docs/guides/redis/scaling/horizontal-scaling/overview.md
- docs/guides/redis/scaling/vertical-scaling/_index.md
- docs/guides/redis/scaling/vertical-scaling/cluster.md
- docs/guides/redis/scaling/vertical-scaling/overview.md
- docs/guides/redis/scaling/vertical-scaling/standalone.md
- docs/guides/redis/upgrading/_index.md
- docs/guides/redis/upgrading/cluster.md
- docs/guides/redis/upgrading/overview.md
- docs/guides/redis/upgrading/standalone.md
Signed-off-by: anis028 <anis028@appscode.com>
> Add enterprise doc and update existing ones

- docs/guides/elasticsearch/clustering/combined-cluster/index.md
- docs/guides/elasticsearch/clustering/combined-cluster/yamls/es-multinode.yaml
- docs/guides/elasticsearch/clustering/combined-cluster/yamls/es-standalone.yaml
- docs/guides/elasticsearch/clustering/topology-cluster/index.md
- docs/guides/elasticsearch/clustering/topology-cluster/yamls/es-topology.yaml
- docs/guides/elasticsearch/concepts/catalog/index.md
- docs/guides/elasticsearch/concepts/elasticsearch-ops-request/index.md
- docs/guides/elasticsearch/concepts/elasticsearch/index.md
- docs/guides/elasticsearch/configuration/combined-cluster/index.md
- docs/guides/elasticsearch/configuration/combined-cluster/yamls/es-combined.yaml
- docs/guides/elasticsearch/configuration/topology-cluster/index.md
- docs/guides/elasticsearch/configuration/topology-cluster/yamls/es-topology.yaml
- docs/guides/elasticsearch/quickstart/overview/index.md
- docs/guides/elasticsearch/quickstart/overview/yamls/elasticsearch.yaml
Signed-off-by: kamolhasan <kamol@appscode.com>
> Update ElasticsearchVersion resource names

- docs/setup/install/community.md
- docs/setup/install/enterprise.md
- docs/setup/uninstall/community.md
> Update set up instructions

- docs/guides/elasticsearch/autoscaler/_index.md
- docs/guides/elasticsearch/autoscaler/compute/_index.md
- docs/guides/elasticsearch/autoscaler/compute/combined/index.md
- docs/guides/elasticsearch/autoscaler/compute/combined/yamls/es-auto-scaler.yaml
- docs/guides/elasticsearch/autoscaler/compute/combined/yamls/es-combined.yaml
- docs/guides/elasticsearch/autoscaler/compute/overview/index.md
- docs/guides/elasticsearch/autoscaler/compute/topology/index.md
- docs/guides/elasticsearch/autoscaler/compute/topology/yamls/es-topology-auto-scaler.yaml
- docs/guides/elasticsearch/autoscaler/compute/topology/yamls/es-topology.yaml
- docs/guides/elasticsearch/autoscaler/storage/_index.md
- docs/guides/elasticsearch/autoscaler/storage/combined/index.md
- docs/guides/elasticsearch/autoscaler/storage/combined/yamls/es-combined-storage-as.yaml
- docs/guides/elasticsearch/autoscaler/storage/combined/yamls/es-combined.yaml
- docs/guides/elasticsearch/autoscaler/storage/overview/index.md
- docs/guides/elasticsearch/autoscaler/storage/topology/index.md
- docs/guides/elasticsearch/autoscaler/storage/topology/yamls/es-topology-storage-as.yaml
- docs/guides/elasticsearch/autoscaler/storage/topology/yamls/es-topology.yaml
- docs/guides/elasticsearch/concepts/autoscaler/index.md
Signed-off-by: kamolhasan <kamol@appscode.com>
> Add Elasticsearch Auto-Scaling Docs

- .github/workflows/preview-website.yml
> Enable website preview for pull requests

- docs/guides/mysql/quickstart/yamls/phpmyadmin.yaml
Add latest version to phpMyAdmin image.
> Add phpmyadmin image version

- docs/reference/operator/kubedb-operator.md
- docs/reference/operator/kubedb-operator_run.md
- docs/reference/operator/kubedb-operator_version.md
> Update docs for kubedb/operator@e48d8929

- docs/reference/cli/kubectl-dba.md
- docs/reference/cli/kubectl-dba_completion.md
- docs/reference/cli/kubectl-dba_describe.md
- docs/reference/cli/kubectl-dba_version.md
> Update docs for kubedb/cli@2b394bba
