kubedb/docs

docs/concepts/what-is-kubedb/overview.md

Markdown.pl requires that a list is separated from previous paragraph by a blank line. Explanation in https://github.github.com/gfm/#example-283.

Make the list of supported DBs look like a list

---

docs/concepts/databases/elasticsearch.md
docs/concepts/databases/memcached.md
docs/concepts/databases/mongodb.md
docs/concepts/databases/mysql.md
docs/concepts/databases/postgres.md
docs/concepts/databases/redis.md

Before if no termination policy was set, we will consider it as DoNotTerminate.
I think this is too restrictive. This blocks namespace deletion.
Now, we only consider explicitly set termination policy.

Change default termination policy as Delete

---

docs/CHANGELOG-v2020.07.10-beta.1.md

Release: v2020.07.10-beta.1
Release-tracker: https://github.com/kubedb/CHANGELOG/pull/3

Prepare for release v2020.07.10-beta.1

---

docs/CHANGELOG-v2020.09.04-beta.0.md

Release: v2020.09.04-beta.0
Release-tracker: https://github.com/kubedb/CHANGELOG/pull/5

Prepare for release v2020.09.04-beta.0

---

docs/examples/mysql/quickstart/demo-1.yaml

the apiVersion: extensions/v1beta has been removed in kubernetes 1.16 in favour of apps/v1. https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/

Change apiVersion for deployment

---

docs/CHANGELOG-v2020.10.26-beta.0.md

Release: v2020.10.26-beta.0
Release-tracker: https://github.com/kubedb/CHANGELOG/pull/16

Prepare for release v2020.10.26-beta.0

---

docs/CHANGELOG-v2020.10.27-rc.0.md

Release: v2020.10.27-rc.0
Release-tracker: https://github.com/kubedb/CHANGELOG/pull/17

Prepare for release v2020.10.27-rc.0

---

docs/CHANGELOG-v2020.10.27-rc.1.md

Release: v2020.10.27-rc.1
Release-tracker: https://github.com/kubedb/CHANGELOG/pull/18

Prepare for release v2020.10.27-rc.1

---

docs/CHANGELOG-v2020.10.27-rc.2.md

Release: v2020.10.27-rc.2
Release-tracker: https://github.com/kubedb/CHANGELOG/pull/19

Prepare for release v2020.10.27-rc.2

---

docs/CHANGELOG-v2020.10.28.md

Release: v2020.10.28
Release-tracker: https://github.com/kubedb/CHANGELOG/pull/21

Prepare for release v2020.10.28

---

docs/CHANGELOG-v2020.11.08.md

Release: v2020.11.08
Release-tracker: https://github.com/kubedb/CHANGELOG/pull/22

Prepare for release v2020.11.08

---

docs/CHANGELOG-v2020.11.11.md

Release: v2020.11.11
Release-tracker: https://github.com/kubedb/CHANGELOG/pull/23

Prepare for release v2020.11.11

---

docs/CHANGELOG-v2020.11.12.md

Release: v2020.11.12
Release-tracker: https://github.com/kubedb/CHANGELOG/pull/24

Prepare for release v2020.11.12

---

docs/CHANGELOG-v2020.12.10.md

Release: v2020.12.10
Release-tracker: https://github.com/kubedb/CHANGELOG/pull/26

Prepare for release v2020.12.10

---

docs/CHANGELOG-v2021.01.02-rc.0.md

Release: v2021.01.02-rc.0
Release-tracker: https://github.com/kubedb/CHANGELOG/pull/28

Prepare for release v2021.01.02-rc.0

---

docs/CHANGELOG-v2021.01.14.md

Release: v2021.01.14
Release-tracker: https://github.com/kubedb/CHANGELOG/pull/29

Prepare for release v2021.01.14

---

docs/CHANGELOG-v2021.01.15.md

Release: v2021.01.15
Release-tracker: https://github.com/kubedb/CHANGELOG/pull/30

Prepare for release v2021.01.15

---

docs/CHANGELOG-v2021.01.26.md

Release: v2021.01.26
Release-tracker: https://github.com/kubedb/CHANGELOG/pull/31

Prepare for release v2021.01.26

---

docs/CHANGELOG-v2021.03.11.md
docs/guides/postgres/README.md
docs/guides/postgres/clustering/streaming_replication.md

Release: v2021.03.11
Release-tracker: https://github.com/kubedb/CHANGELOG/pull/34

Prepare for release v2021.03.11

---

docs/CHANGELOG-v2021.03.17.md

Release: v2021.03.17
Release-tracker: https://github.com/kubedb/CHANGELOG/pull/35

Prepare for release v2021.03.17

---

docs/CHANGELOG-v2021.04.16.md

Release: v2021.04.16
Release-tracker: https://github.com/kubedb/CHANGELOG/pull/37

Prepare for release v2021.04.16

---

docs/CHANGELOG-v2021.06.23.md

Release: v2021.06.23
Release-tracker: https://github.com/kubedb/CHANGELOG/pull/39

Prepare for release v2021.06.23
